produit_homepage:
    path:     /
    defaults: { _controller: ProduitBundle:Default:index }

produit_Afficher:
    path:     /admin/AfficherProduit
    defaults: { _controller: ProduitBundle:Produit:AfficheProduit }

produit_Supprimer:
    path:     /admin/deleteProduit/{id}
    defaults: { _controller: ProduitBundle:Produit:deleteProduit }


produit_Modifier:
    path:     /admin/ModifierProduit/{id}
    defaults: { _controller: ProduitBundle:Produit:ModifierProduit }

Promotion_Ajout:
    path:     /admin/ajouterPromotion
    defaults: { _controller: ProduitBundle:Promotion:AjoutPromotion }

Promotion_Affiche:
    path:     /admin/AfficherPromotion
    defaults: { _controller: ProduitBundle:Promotion:AffichePromotion }


Promotion_Delete:
    path:     /admin/DeletePromotion/{id}
    defaults: { _controller: ProduitBundle:Promotion:deletePromotion }

Promotion_Modifier:
    path:     /admin/ModifierPromotion/{id}
    defaults: { _controller: ProduitBundle:Promotion:ModifierPromotion }

Poromo_Front:
    path:     /Client/AfficherPromoFront
    defaults: { _controller: ProduitBundle:Promotion:AffichePromotionFront }

Produit_Front:
    path:     /Client/AfficherProduitFront
    defaults: { _controller: ProduitBundle:Produit:AfficheProduitFront }
Produit_mob:
    path:     /ProduitsMob
    defaults: { _controller: ProduitBundle:Produit:AfficheProduitMobile }
Produit_mobPromo:
    path:     /ProduitsMobPromo
    defaults: { _controller: ProduitBundle:Promotion:AfficheProduitMobilePromo }
Produit_mobADD:
    path:     /AddProductMob
    defaults: { _controller: ProduitBundle:Produit:AddProductMob }
Produit_mobDelete:
        path:     /DeleteProductMob/{id}
        defaults: { _controller: ProduitBundle:Produit:C }
Produit_mobModif:
        path:  /ModiferStockMobile/{id}/{nom}/{prix}/{quantite}
        defaults: { _controller: ProduitBundle:Produit:ModiferStockMobile }
Promo_mobADD:
            path:  /AddPromoMob
            defaults: { _controller: ProduitBundle:Produit:AddPromotionMob }


